apiVersion: v1
kind: Service
metadata:
  name: df-bridge
  namespace: odyssey
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32513
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: df-bridge
  type: NodePort
