apiVersion: v1
kind: Service
metadata:
  name: df-bridge
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"443":{"name": "df-bridge"}}}'
spec:
  type: ClusterIP
  selector:
    run: df-bridge # Selects Pods labelled run: neg-demo-app
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443