apiVersion: v1
kind: Service
metadata:
  name: df-webhook
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "df-webhook-neg"}}}'
spec:
  type: ClusterIP
  selector:
    run: df-webhook # Selects Pods labelled run: neg-demo-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000